### 更新 CWA 天氣資料
POST http://127.0.0.1:5000/api/weather/refresh
Content-Type: application/json

{}

###
GET http://127.0.0.1:5000/api/townships/%E4%B8%AD%E5%8D%80/weather
### 從 SQLite 取得天氣資料
GET http://127.0.0.1:5000/api/weather

### 取得鄉鎮資料
GET http://127.0.0.1:5000/api/townships

### 從 SQLite 取得縣市座標
GET http://127.0.0.1:5000/api/locations

### 取得所有縣市 7 天天氣
GET http://127.0.0.1:5000/api/weather/weekly